export enum CustomerPain {
  UNDEFINED = 'UNDEFINED',
  HIGH_VOLUME_INTERACTIONS = 'HIGH_VOLUME_INTERACTIONS',
  MANUAL_PROCESS_INEFFICIENCY = 'MANUAL_PROCESS_INEFFICIENCY',
  RESPONSE_TIME_DELAYS = 'RESPONSE_TIME_DELAYS',
  SCALABILITY_ISSUES = 'SCALABILITY_ISSUES',
  TEAM_OVERLOAD = 'TEAM_OVERLOAD',
  LACK_OF_AUTOMATION = 'LACK_OF_AUTOMATION',
  CUSTOMER_EXPERIENCE_DEGRADATION = 'CUSTOMER_EXPERIENCE_DEGRADATION',
  PEAK_SEASON_OVERLOAD = 'PEAK_SEASON_OVERLOAD',
  OTHER = 'OTHER',
}
