export enum PurchaseObjection {
  UNDEFINED = 'UNDEFINED',
  TECHNOLOGY_CONCERNS = 'TECHNOLOGY_CONCERNS',
  DATA_CONFIDENTIALITY = 'DATA_CONFIDENTIALITY',
  LOSS_OF_PERSONAL_TOUCH = 'LOSS_OF_PERSONAL_TOUCH',
  INTEGRATION_COMPLEXITY = 'INTEGRATION_COMPLEXITY',
  BUDGET_CONSTRAINTS = 'BUDGET_CONSTRAINTS',
  UNCERTAINTY_ABOUT_RESULTS = 'UNCERTAINTY_ABOUT_RESULTS',
  COMPATIBILITY_ISSUES = 'COMPATIBILITY_ISSUES',
  IMPLEMENTATION_EFFORT = 'IMPLEMENTATION_EFFORT',
  OTHER = 'OTHER',
}
