export enum VambeDiscoverySource {
  UNDEFINED = 'UNDEFINED',
  CONFERENCE = 'CONFERENCE',
  GOOGLE_SEARCH = 'GOOGLE_SEARCH',
  COLLEAGUE_RECOMMENDATION = 'COLLEAGUE_RECOMMENDATION',
  LINKEDIN = 'LINKEDIN',
  PODCAST = 'PODCAST',
  ONLINE_ARTICLE = 'ONLINE_ARTICLE',
  FORUM_GROUP = 'FORUM_GROUP',
  NETWORKING_EVENT = 'NETWORKING_EVENT',
  OTHER = 'OTHER',
}
